# ==============================
# Perfil: LOCAL (docker-compose)
# Ativar com: --spring.profiles.active=local
# ==============================

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/fixflow
spring.datasource.username=fixflow
spring.datasource.password=fixflow
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=fixflow
spring.rabbitmq.password=fixflow

# Logging
logging.level.com.periclao.fixflow=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
